dist: xenial
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=lint
install:
  - pip install tox
script: tox
after_success:
  - pip install coveralls
  - coveralls
